version: "3.9"

services:
  # MySQL database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}  # Root password is required for MySQL
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - eCommerce_data_handler:/var/lib/mysql
    networks:
      - eCommerce_data_handler_net

  # Adminer for database UI
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports: 
      - 3333:8080
    networks:
      - eCommerce_data_handler_net

  # MinIO as an S3-compatible (raw)data lake.
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASS}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-webhook-queue:/tmp/webhook_queue


networks:
  eCommerce_data_handler_net:

volumes:
  eCommerce_data_handler:
